In [1]:
import pandas as pd

# path CSV file
file_path = '/kaggle/input/malaria/malaria.csv'

# Read CSV file into a Pandas DataFrame
data = pd.read_csv(file_path)

print(data.columns)

Index(['#Wave', '#Intensity'], dtype='object')


In [2]:
# SPLIT BY ARRAYS (NUMPY)
import numpy as np
import pandas as pd

# Path to CSV file
file_path = '/kaggle/input/malaria/malaria.csv'

# Read CSV file into Pandas DataFrame (NumPy array)
data = pd.read_csv(file_path)

# Convert relevant columns to NumPy array
np_data = data[['#Wave', '#Intensity']].to_numpy()

# Find indices where new spectrum begins
new_spectrum_indices = np.where(np_data[:, 0] == 1705.003906)[0]

# Split data into individual spectra based on identified indices
spectra_list = np.split(np_data, new_spectrum_indices)

# Access individual spectra
for i, spectrum in enumerate(spectra_list):
    print(f"Spectrum {i + 1}:\n{spectra_list[i]}")

Spectrum 1:
[]
Spectrum 2:
[[1705.003906   98.839386]
 [1703.941406   87.072792]
 [1702.878906  101.175087]
 ...
 [ 520.828125   54.147247]
 [ 519.535156   46.401585]
 [ 518.242188   52.190144]]
Spectrum 3:
[[1705.003906  155.319031]
 [1703.941406  138.84581 ]
 [1702.878906  159.997818]
 ...
 [ 520.828125   65.750229]
 [ 519.535156   56.068581]
 [ 518.242188   73.452797]]
Spectrum 4:
[[1705.003906  202.385406]
 [1703.941406  192.972137]
 [1702.878906  204.703079]
 ...
 [ 520.828125   75.41938 ]
 [ 519.535156   85.069572]
 [ 518.242188   65.720924]]
Spectrum 5:
[[1705.003906  235.331879]
 [1703.941406  270.631653]
 [1702.878906  232.937988]
 ...
 [ 520.828125   94.757683]
 [ 519.535156   81.202774]
 [ 518.242188  100.514351]]
Spectrum 6:
[[1705.003906  265.925018]
 [1703.941406  249.451782]
 [1702.878906  237.643814]
 ...
 [ 520.828125   98.625343]
 [ 519.535156   92.803169]
 [ 518.242188   85.050606]]
Spectrum 7:
[[1705.003906  272.984985]
 [1703.941406  284.751556]
 [1702.878906  277.

In [3]:
# SPLIT BY COLUMNS NAMES (PANDAS)
import pandas as pd

# Path to CSV file
file_path = '/kaggle/input/malaria/malaria.csv'

# Read CSV file into Pandas DataFrame
data = pd.read_csv(file_path)

# Find indices where new spectrum begins
new_spectrum_indices = data.index[data['#Wave'] == 1705.003906].tolist()

# Create an empty list to store individual spectra
spectra_list = []

# Split data into individual spectra based on identified indices
for i in range(len(new_spectrum_indices) - 1):
    start_index = new_spectrum_indices[i]
    end_index = new_spectrum_indices[i + 1]
    spectrum = data.iloc[start_index:end_index]
    spectra_list.append(spectrum)

# Append last spectrum (from last detected new_spectrum_indices to end of data)
spectra_list.append(data.iloc[new_spectrum_indices[-1]:])

# Access individual spectra
for i, spectrum in enumerate(spectra_list):
    print(f"Spectrum {i + 1}:\n{spectra_list[i]}")

Spectrum 1:
            #Wave  #Intensity
0     1705.003906   98.839386
1     1703.941406   87.072792
2     1702.878906  101.175087
3     1701.816406   98.804962
4     1700.753906  103.491920
...           ...         ...
1010   523.414063   44.497906
1011   522.121094   54.159309
1012   520.828125   54.147247
1013   519.535156   46.401585
1014   518.242188   52.190144

[1015 rows x 2 columns]
Spectrum 2:
            #Wave  #Intensity
1015  1705.003906  155.319031
1016  1703.941406  138.845810
1017  1702.878906  159.997818
1018  1701.816406  178.789932
1019  1700.753906  166.998337
...           ...         ...
2025   523.414063   56.106056
2026   522.121094   69.633392
2027   520.828125   65.750229
2028   519.535156   56.068581
2029   518.242188   73.452797

[1015 rows x 2 columns]
Spectrum 3:
            #Wave  #Intensity
2030  1705.003906  202.385406
2031  1703.941406  192.972137
2032  1702.878906  204.703079
2033  1701.816406  221.134918
2034  1700.753906  185.815048
...           